
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int STRLIT = 51;
  public static final int LOGAND = 22;
  public static final int LTE = 17;
  public static final int INCREMENT = 30;
  public static final int MULT = 9;
  public static final int POS = 12;
  public static final int CHAR = 40;
  public static final int EQUALS = 3;
  public static final int NEGA = 14;
  public static final int NOTEQUAL = 19;
  public static final int SEMI = 2;
  public static final int INT = 38;
  public static final int PRINTLN = 7;
  public static final int MINUS = 13;
  public static final int DECREMENT = 31;
  public static final int CLOSEPAREN = 24;
  public static final int TILDE = 29;
  public static final int INTLIT = 48;
  public static final int OPENPAREN = 23;
  public static final int LT = 15;
  public static final int COND2 = 33;
  public static final int COND1 = 32;
  public static final int BOOL = 41;
  public static final int COMMA = 34;
  public static final int CLASS = 4;
  public static final int FI = 46;
  public static final int DIV = 10;
  public static final int PLUS = 11;
  public static final int IF = 42;
  public static final int ID = 47;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int VOID = 37;
  public static final int OPENSQUARE = 25;
  public static final int CLOSECURLY = 28;
  public static final int FLOATLIT = 49;
  public static final int GTE = 18;
  public static final int CHARLIT = 50;
  public static final int OPENCURLY = 27;
  public static final int ELSE = 44;
  public static final int READ = 5;
  public static final int FINAL = 45;
  public static final int WHILE = 43;
  public static final int LOGOR = 21;
  public static final int FLOAT = 39;
  public static final int LOGEQUALS = 20;
  public static final int FALSE = 36;
  public static final int CLOSESQUARE = 26;
  public static final int GT = 16;
  public static final int PRINT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "EQUALS",
  "CLASS",
  "READ",
  "PRINT",
  "PRINTLN",
  "RETURN",
  "MULT",
  "DIV",
  "PLUS",
  "POS",
  "MINUS",
  "NEGA",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "NOTEQUAL",
  "LOGEQUALS",
  "LOGOR",
  "LOGAND",
  "OPENPAREN",
  "CLOSEPAREN",
  "OPENSQUARE",
  "CLOSESQUARE",
  "OPENCURLY",
  "CLOSECURLY",
  "TILDE",
  "INCREMENT",
  "DECREMENT",
  "COND1",
  "COND2",
  "COMMA",
  "TRUE",
  "FALSE",
  "VOID",
  "INT",
  "FLOAT",
  "CHAR",
  "BOOL",
  "IF",
  "WHILE",
  "ELSE",
  "FINAL",
  "FI",
  "ID",
  "INTLIT",
  "FLOATLIT",
  "CHARLIT",
  "STRLIT"
  };
}

